# Configuration pour le site GitHub Pages utilisant Jekyll

# Thème local
theme: jekyll-theme-cayman

# Thème distant
remote_theme: "pages-themes/cayman@v0.2.0"

# Plugins Jekyll
plugins:
  - jekyll-remote-theme

# Groupes de gems pour les plugins Jekyll
gem:
  "github-pages":
    group: :jekyll_plugins

title: "Portfolio"
description: "Showcasing my learning projects"
show_downloads: false
google_analytics: ## UA-XXXXXXXX-X

# Custom navigation
navigation:
  - name: "Home"
    link: /
  - name: "About Me"
    link: /about
  - name: "Projects"
    link: /index.md
  - name: "Contact"
    link: /contact

